module.exports = {
  rules: {
    'no-debugger': 2,
    'no-console': 1,
    'array-callback-return': [2, { allowImplicit: true }],
    'class-methods-use-this': [
      2,
      {
        exceptMethods: [
          'render',
          'getInitialState',
          'getDefaultProps',
          'getChildContext',
          'componentWillMount',
          'componentDidMount',
          'componentWillReceiveProps',
          'shouldComponentUpdate',
          'componentWillUpdate',
          'componentDidUpdate',
          'componentWillUnmount',
        ],
      },
    ],
    'lines-between-class-members': [2, 'always', { exceptAfterSingleLine: true }],
    'consistent-return': 1,
    'default-case': 2,
    'dot-notation': [2, { allowKeywords: true }],
    eqeqeq: [2, 'always', { null: 'ignore' }],
    'guard-for-in': 2,
    'max-classes-per-file': [2, 1],
    'no-alert': 2,
    'no-caller': 2,
    'no-case-declarations': 2,
    'no-empty-function': 2,
    'no-empty-pattern': 2,
    'no-eval': 2,
    'no-extend-native': 2,
    'no-extra-bind': 2,
    'no-extra-label': 2,
    'no-fallthrough': 2,
    'no-floating-decimal': 2,
    'no-global-assign': [2, { exceptions: [] }],
    'no-implied-eval': 2,
    'no-labels': 2,
    'no-lone-blocks': 2,
    'no-loop-func': 2,
    'no-multi-spaces': [
      'error',
      {
        ignoreEOLComments: false,
      },
    ],
    'no-new': 2,
    'no-new-func': 2,
    'no-new-wrappers': 2,
    'no-octal': 2,
    'no-octal-escape': 2,
    'no-param-reassign': [
      2,
      {
        props: true,
        ignorePropertyModificationsFor: ['acc', 'arr', 'obj'],
      },
    ],
    'no-proto': 2,
    'no-restricted-properties': 2,
    'no-return-assign': [2, 'always'],
    'no-return-await': 2,
    'no-script-url': 2,
    'no-self-assign': 2,
    'no-self-compare': 2,
    'no-sequences': 2,
    'no-throw-literal': 2,
    'no-unused-expressions': [2, { allowTernary: true }],
    'no-useless-catch': 2,
    'no-useless-concat': 2,
    'no-useless-escape': 2,
    'no-useless-return': 2,
    'no-void': 2,
    'no-with': 2,
    'no-underscore-dangle': 2,
    'prefer-promise-reject-errors': [2, { allowEmptyReject: true }],
    radix: 2,
    'vars-on-top': 2,
    yoda: 2,
  },
};
