import { BusinessType, RelationshipToBusiness } from 'app/types/businesses';

export const BUSINESS_TYPES: Readonly<Record<BusinessType, string>> = {
  [BusinessType.SINGLE_MEMBER_LLC]: 'Limited Liability Company',
  [BusinessType.MULTI_MEMBER_LLC]: 'Limited Liability Partnership',
  [BusinessType.SOLE_PROPRIETORSHIP]: 'Sole Proprietorship',
  [BusinessType.PRIVATE_CORPORATION]: 'Private Corporation',
  [BusinessType.PRIVATE_PARTNERSHIP]: 'Private Partnership',
  [BusinessType.PUBLIC_CORPORATION]: 'Public Corporation',
  [BusinessType.PUBLIC_PARTNERSHIP]: 'Public Partnership',
  [BusinessType.INCORPORATED_NON_PROFIT]: 'Incorporated non-profit',
  [BusinessType.UNKNOWN]: 'Unknown',
  [BusinessType.OTHER]: "Other / I'm not sure",
};

export const RELATIONSHIP_TO_BUSINESS: Readonly<Record<RelationshipToBusiness, string>> = {
  [RelationshipToBusiness.OWNER]: 'Owner',
  [RelationshipToBusiness.REPRESENTATIVE]: 'Representative',
  [RelationshipToBusiness.EXECUTIVE]: 'Executive',
  [RelationshipToBusiness.DIRECTOR]: 'Director',
  [RelationshipToBusiness.OTHER]: 'Other',
};

export const USA_STATES: Readonly<Record<string, string>> = {
  AL: 'Alabama',
  AK: 'Alaska',
  AZ: 'Arizona',
  AR: 'Arkansas',
  CA: 'California',
  CO: 'Colorado',
  CT: 'Connecticut',
  DE: 'Delaware',
  DC: 'District of Columbia',
  FL: 'Florida',
  GA: 'Georgia',
  HI: 'Hawaii',
  ID: 'Idaho',
  IL: 'Illinois',
  IN: 'Indiana',
  IA: 'Iowa',
  KS: 'Kansas',
  KY: 'Kentucky',
  LA: 'Louisiana',
  ME: 'Maine',
  MD: 'Maryland',
  MA: 'Massachusetts',
  MI: 'Michigan',
  MN: 'Minnesota',
  MS: 'Mississippi',
  MO: 'Missouri',
  MT: 'Montana',
  NE: 'Nebraska',
  NV: 'Nevada',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NM: 'New Mexico',
  NY: 'New York',
  NC: 'North Carolina',
  ND: 'North Dakota',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  PA: 'Pennsylvania',
  RI: 'Rhode Island',
  SC: 'South Carolina',
  SD: 'South Dakota',
  TN: 'Tennessee',
  TX: 'Texas',
  UT: 'Utah',
  VT: 'Vermont',
  VA: 'Virginia',
  WA: 'Washington',
  WV: 'West Virginia',
  WI: 'Wisconsin',
  WY: 'Wyoming',
};
