/*
  Rules for adding new icons

  - All icons should be optimised by some tool (for example https://jakearchibald.github.io/svgomg/);
  - All icons should have `24x24` size;
  - All elements in single-color icons should have `currentColor` color value;
*/

export enum IconName {
  accounting = 'accounting',
  add = 'add',
  'add-receipt' = 'add-receipt',
  'add-circle-outline' = 'add-circle-outline',
  amount = 'amount',
  allocations = 'allocations',
  alert = 'alert',
  approvals = 'approvals',
  'arrow-down' = 'arrow-down',
  'arrow-left' = 'arrow-left',
  'arrow-right' = 'arrow-right',
  'audit-logs' = 'audit-logs',
  calendar = 'calendar',
  cancel = 'cancel',
  'cancel-circle' = 'cancel-circle',
  'cancel-rounded' = 'cancel-rounded',
  card = 'card',
  'card-add-new' = 'card-add-new',
  'card-fill' = 'card-fill',
  'card-success' = 'card-success',
  'channel-atm' = 'channel-atm',
  'channel-ecommerce' = 'channel-ecommerce',
  'channel-moto' = 'channel-moto',
  'channel-subscription' = 'channel-subscription',
  'chevron-down' = 'chevron-down',
  'chevron-left' = 'chevron-left',
  'chevron-right' = 'chevron-right',
  clock = 'clock',
  'clock-fill' = 'clock-fill',
  company = 'company',
  confirm = 'confirm',
  'confirm-circle' = 'confirm-circle',
  'confirm-circle-filled' = 'confirm-circle-filled',
  'confirm-square-filled' = 'confirm-square-filled',
  connect = 'connect',
  copy = 'copy',
  dashboard = 'dashboard',
  dollars = 'dollars',
  download = 'download',
  edit = 'edit',
  email = 'email',
  employees = 'employees',
  'error-circle' = 'error-circle',
  file = 'file',
  'file-text' = 'file-text',
  filters = 'filters',
  freeze = 'freeze',
  globe = 'globe',
  information = 'information',
  keyboard = 'keyboard',
  'l-tab' = 'l-tab',
  lock = 'lock',
  'mcc-child-care' = 'mcc-child-care',
  'mcc-digital-goods' = 'mcc-digital-goods',
  'mcc-education' = 'mcc-education',
  'mcc-entertainment' = 'mcc-entertainment',
  'mcc-food-and-beverage' = 'mcc-food-and-beverage',
  'mcc-gambling' = 'mcc-gambling',
  'mcc-government' = 'mcc-government',
  'mcc-health' = 'mcc-health',
  'mcc-memberships' = 'mcc-memberships',
  'mcc-money-transfer' = 'mcc-money-transfer',
  'mcc-services' = 'mcc-services',
  'mcc-shopping' = 'mcc-shopping',
  'mcc-travel' = 'mcc-travel',
  'mcc-utilities' = 'mcc-utilities',
  'merchant-services' = 'merchant-services',
  'more-horizontal' = 'more-horizontal',
  'more-vertical' = 'more-vertical',
  'payment-bank' = 'payment-bank',
  'payment-card' = 'payment-card',
  pdf = 'pdf',
  phone = 'phone',
  photo = 'photo',
  pin = 'pin',
  power = 'power',
  receipt = 'receipt',
  'receipt-unavailable' = 'receipt-unavailable',
  refresh = 'refresh',
  search = 'search',
  settings = 'settings',
  sync = 'sync',
  'table-columns' = 'table-columns',
  tag = 'tag',
  transaction = 'transaction',
  trash = 'trash',
  upload = 'upload',
  user = 'user',
  'user-super' = 'user-super',
  view = 'view',
  'warning-rounded' = 'warning-rounded',
  'warning-triangle' = 'warning-triangle',
  'z-placeholder' = 'z-placeholder',
}
