export enum BusinessStatus {
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
  ONBOARDING = 'ONBOARDING',
  SUSPENDED = 'SUSPENDED',
}

// From ConvertBusinessProspectRequest['businessType']
export enum BusinessType {
  'INDIVIDUAL',
  'SOLE_PROPRIETORSHIP',
  'SINGLE_MEMBER_LLC',
  'MULTI_MEMBER_LLC',
  'PRIVATE_PARTNERSHIP',
  'PUBLIC_PARTNERSHIP',
  'PRIVATE_CORPORATION',
  'PUBLIC_CORPORATION',
  'INCORPORATED_NON_PROFIT',
}

export enum OnboardingStep {
  BUSINESS_OWNERS = 'BUSINESS_OWNERS',
  LINK_ACCOUNT = 'LINK_ACCOUNT',
  REVIEW = 'REVIEW',
  SOFT_FAIL = 'SOFT_FAIL',
  TRANSFER_MONEY = 'TRANSFER_MONEY',
  COMPLETE = 'COMPLETE',
}
