export const TEMP_QBO_EXPENSE_CATEGORIES = [
  {
    id: '80',
    name: 'Cost of Goods Sold',
    fullyQualifiedCategory: 'Expense.Cost of Goods Sold.SuppliesMaterialsCogs',
    fullyQualifiedName: 'Expense.Cost of Goods Sold.SuppliesMaterialsCogs.Cost of Goods Sold',
    currency: 'USD',
    currentBalance: 0.0,
    type: 'Expense',
    status: 'Active',
    isBankAccount: false,
  },
  {
    id: '7',
    name: 'Advertising',
    fullyQualifiedCategory: 'Expense.Expense.AdvertisingPromotional',
    fullyQualifiedName: 'Expense.Expense.AdvertisingPromotional.Advertising',
    currency: 'USD',
    currentBalance: 0.0,
    type: 'Expense',
    status: 'Active',
    isBankAccount: false,
  },
  {
    id: '91',
    name: 'fdfsdfsdsdfdsdff',
    fullyQualifiedCategory: 'Expense.Expense.AdvertisingPromotional',
    fullyQualifiedName: 'Expense.Expense.AdvertisingPromotional.fdfsdfsdsdfdsdff',
    currency: 'USD',
    currentBalance: 0.0,
    type: 'Expense',
    status: 'Active',
    isBankAccount: false,
  },
  {
    id: '16',
    name: 'Promotional',
    fullyQualifiedCategory: 'Expense.Expense.AdvertisingPromotional',
    fullyQualifiedName: 'Expense.Expense.AdvertisingPromotional.Promotional',
    currency: 'USD',
    currentBalance: 0.0,
    type: 'Expense',
    status: 'Active',
    isBankAccount: false,
  },
  {
    id: '55',
    name: 'Automobile',
    fullyQualifiedCategory: 'Expense.Expense.Auto',
    fullyQualifiedName: 'Expense.Expense.Auto.Automobile',
    currency: 'USD',
    currentBalance: 0.0,
    type: 'Expense',
    status: 'Active',
    isBankAccount: false,
  },
  {
    id: '56',
    name: 'Fuel',
    fullyQualifiedCategory: 'Expense.Expense.Auto',
    fullyQualifiedName: 'Expense.Expense.Auto.Fuel',
    currency: 'USD',
    currentBalance: 0.0,
    type: 'Expense',
    status: 'Active',
    isBankAccount: false,
  },
  {
    id: '8',
    name: 'Bank Charges',
    fullyQualifiedCategory: 'Expense.Expense.BankCharges',
    fullyQualifiedName: 'Expense.Expense.BankCharges.Bank Charges',
    currency: 'USD',
    currentBalance: 0.0,
    type: 'Expense',
    status: 'Active',
    isBankAccount: false,
  },
  {
    id: '10',
    name: 'Dues & Subscriptions',
    fullyQualifiedCategory: 'Expense.Expense.DuesSubscriptions',
    fullyQualifiedName: 'Expense.Expense.DuesSubscriptions.Dues & Subscriptions',
    currency: 'USD',
    currentBalance: 0.0,
    type: 'Expense',
    status: 'Active',
    isBankAccount: false,
  },
  {
    id: '13',
    name: 'Meals and Entertainment',
    fullyQualifiedCategory: 'Expense.Expense.EntertainmentMeals',
    fullyQualifiedName: 'Expense.Expense.EntertainmentMeals.Meals and Entertainment',
    currency: 'USD',
    currentBalance: 0.0,
    type: 'Expense',
    status: 'Active',
    isBankAccount: false,
  },
  {
    id: '29',
    name: 'Equipment Rental',
    fullyQualifiedCategory: 'Expense.Expense.EquipmentRental',
    fullyQualifiedName: 'Expense.Expense.EquipmentRental.Equipment Rental',
    currency: 'USD',
    currentBalance: 0.0,
    type: 'Expense',
    status: 'Active',
    isBankAccount: false,
  },
  {
    id: '62',
    name: 'Equipment Rental',
    fullyQualifiedCategory: 'Expense.Expense.EquipmentRental',
    fullyQualifiedName: 'Expense.Expense.EquipmentRental.Equipment Rental',
    currency: 'USD',
    currentBalance: 0.0,
    type: 'Expense',
    status: 'Active',
    isBankAccount: false,
  },
  {
    id: '11',
    name: 'Insurance',
    fullyQualifiedCategory: 'Expense.Expense.Insurance',
    fullyQualifiedName: 'Expense.Expense.Insurance.Insurance',
    currency: 'USD',
    currentBalance: 0.0,
    type: 'Expense',
    status: 'Active',
    isBankAccount: false,
  },
  {
    id: '57',
    name: 'Workers Compensation',
    fullyQualifiedCategory: 'Expense.Expense.Insurance',
    fullyQualifiedName: 'Expense.Expense.Insurance.Workers Compensation',
    currency: 'USD',
    currentBalance: 0.0,
    type: 'Expense',
    status: 'Active',
    isBankAccount: false,
  },
  {
    id: '70',
    name: 'Bookkeeper',
    fullyQualifiedCategory: 'Expense.Expense.LegalProfessionalFees',
    fullyQualifiedName: 'Expense.Expense.LegalProfessionalFees.Bookkeeper',
    currency: 'USD',
    currentBalance: 0.0,
    type: 'Expense',
    status: 'Active',
    isBankAccount: false,
  },
  {
    id: '71',
    name: 'Lawyer',
    fullyQualifiedCategory: 'Expense.Expense.LegalProfessionalFees',
    fullyQualifiedName: 'Expense.Expense.LegalProfessionalFees.Lawyer',
    currency: 'USD',
    currentBalance: 0.0,
    type: 'Expense',
    status: 'Active',
    isBankAccount: false,
  },
  {
    id: '15',
    name: 'Office Expenses',
    fullyQualifiedCategory: 'Expense.Expense.OfficeGeneralAdministrativeExpenses',
    fullyQualifiedName: 'Expense.Expense.OfficeGeneralAdministrativeExpenses.Office Expenses',
    currency: 'USD',
    currentBalance: 0.0,
    type: 'Expense',
    status: 'Active',
    isBankAccount: false,
  },
  {
    id: '19',
    name: 'Stationery & Printing',
    fullyQualifiedCategory: 'Expense.Expense.OfficeGeneralAdministrativeExpenses',
    fullyQualifiedName: 'Expense.Expense.OfficeGeneralAdministrativeExpenses.Stationery & Printing',
    currency: 'USD',
    currentBalance: 0.0,
    type: 'Expense',
    status: 'Active',
    isBankAccount: false,
  },
  {
    id: '28',
    name: 'Disposal Fees',
    fullyQualifiedCategory: 'Expense.Expense.OtherMiscellaneousServiceCost',
    fullyQualifiedName: 'Expense.Expense.OtherMiscellaneousServiceCost.Disposal Fees',
    currency: 'USD',
    currentBalance: 0.0,
    type: 'Expense',
    status: 'Active',
    isBankAccount: false,
  },
  {
    id: '60',
    name: 'Installation',
    fullyQualifiedCategory: 'Expense.Expense.OtherMiscellaneousServiceCost',
    fullyQualifiedName: 'Expense.Expense.OtherMiscellaneousServiceCost.Installation',
    currency: 'USD',
    currentBalance: 0.0,
    type: 'Expense',
    status: 'Active',
    isBankAccount: false,
  },
  {
    id: '61',
    name: 'Maintenance and Repairs',
    fullyQualifiedCategory: 'Expense.Expense.OtherMiscellaneousServiceCost',
    fullyQualifiedName: 'Expense.Expense.OtherMiscellaneousServiceCost.Maintenance and Repairs',
    currency: 'USD',
    currentBalance: 0.0,
    type: 'Expense',
    status: 'Active',
    isBankAccount: false,
  },
];
