export const Events = {
  CREATE_ALLOCATION: 'Create Allocation',
  CREATE_CARD: 'Create Card',
  CREATE_EMPLOYEE: 'Create Employee',
  POST_ERROR: 'POST Error',
  POST_SUCCESS: 'POST Success',
  PUT_ERROR: 'PUT Error',
  PUT_SUCCESS: 'PUT Success',
  GET_ERROR: 'GET Error',
  GET_SUCCESS: 'GET Success',
  DELETE_ERROR: 'DELETE Error',
  DELETE_SUCCESS: 'DELETE Success',
  PATCH_ERROR: 'PATCH Error',
  PATCH_SUCCESS: 'PATCH Success',
  LOGIN: 'Login',
  SIGNUP: 'Create Employee',
  UPDATE_ALLOCATION: 'Update Allocation',
  UPDATE_CARD: 'Update Card',
  UPDATE_EMPLOYEE: 'Update Employee',
};
